Repository orijoon98/Tetris_SE4, pull requests merged in 2022-04, with the labels that each got.

#6 branch/#2
  .gitignore
  src/main/java/component/Game.java
  src/main/java/component/Home.java
  src/main/java/component/ScoreBoard.java
  src/main/java/component/Setting.java
  src/main/java/component/game/Board.java
  src/main/java/component/game/BoardCell.java
  src/main/java/component/game/GameGUI.java
  src/main/java/component/game/GameSetting.java
  src/main/java/input/GameInput.java
Labels: ✨ Feature

#11 branch/#3
  src/main/java/component/Game.java
  src/main/java/component/Home.java
  src/main/java/component/ScoreBoard.java
  src/main/java/component/Setting.java
  src/main/java/component/game/GameGUI.java
  src/main/java/input/GameInput.java
Labels: 🐞 BugFix, ✨ Feature

#12 branch/#3
  src/main/java/component/Home.java
  src/main/java/component/ScoreBoard.java
  src/main/java/component/Setting.java
Labels: 🎨 Design

#16 branch/#11
  src/main/java/component/Home.java
  src/main/java/component/ScoreBoard.java
  src/main/java/component/ScoreBoardItem.java
  src/main/java/component/ScoreBoardNormal.java
  src/main/java/input/ScoreBoardInput.java
  src/main/java/input/ScoreBoardItemInput.java
  src/main/java/input/ScoreBoardNormalInput.java
  src/main/java/thread/ScoreBoardItemLoop.java
  src/main/java/thread/ScoreBoardLoop.java
  src/main/java/thread/ScoreBoardNormalLoop.java
Labels: 🎨 Design, 🐞 BugFix, ✨ Feature

#19 branch/#7
  src/main/java/component/Game.java
  src/main/java/input/GameInput.java
Labels: 🎨 Design, ✨ Feature

#20 branch/#7
  build.gradle
  src/main/java/component/ScoreBoard.java
Labels: ✨ Feature

#21 branch/#7
  src/main/java/component/Game.java
  src/main/java/component/Home.java
  src/main/java/component/NormalGameOver.java
  src/main/java/component/ScoreBoard.java
  src/main/java/component/ScoreBoardItem.java
  src/main/java/component/ScoreBoardNormal.java
  src/main/java/thread/GameLoop.java
Labels: ✨ Feature

#22 branch/#8
  src/main/java/component/game/GameSetting.java
Labels: ✨ Feature

#24 branch/#7
  src/test/java/component/game/BoardTest.java
Labels: ✅ Test

#30 branch/#12
  src/main/java/component/Setting.java
Labels: ✨ Feature
